# Add Format Version section here.
AWSTemplateFormatVersion: '2010-09-09'

# Add Description section here.
Description : 'AWS CloudFormation Workshop template.'

# Add Metadata section here.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Amazon EC2 Configuration'
        Parameters:
          - InstanceType

    ParameterLabels:
      InstanceType:
        default: 'Type of EC2 Instance'


# Add Parameters section here.
Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: 'Enter t2.micro, m1.small, or m1.large. Default is t2.micro.'


# aws ssm get-parameters \
# --names /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2 \
# --query "Parameters[].Value" \
# --region eu-west-2 \
# --output text

# Add Resources section here.
Resources:
  WebServerInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-0dacb0c129b49f529
