# Add Format Version section here.
AWSTemplateFormatVersion: '2010-09-09'


# Add Description section here.

# Add Metadata section here.

# Add Parameters section here.

# Add Resources section here.